import os

UNIVERISTY_NAME = os.getenv("UNIVERISTY_NAME")

#### Data Bases Connections ####

# Oracle: 
ORIGIN_1_NAME = os.getenv("ORIGIN_1_NAME")
ORIGIN_1_HOST_NAME = os.getenv("ORIGIN_1_HOST_NAME")
ORIGIN_1_PORT = os.getenv("ORIGIN_1_PORT")
ORIGIN_1_SERVICE_NAME = os.getenv("ORIGIN_1_SERVICE_NAME")
ORIGIN_1_USER = os.getenv("ORIGIN_1_USER")
ORIGIN_1_PASSWORD = os.getenv("ORIGIN_1_PASSWORD")


# Oracle: 
ORIGIN_2_NAME = os.getenv("ORIGIN_2_NAME")
ORIGIN_2_HOST_NAME = os.getenv("ORIGIN_2_HOST_NAME")
ORIGIN_2_PORT = os.getenv("ORIGIN_2_PORT")
ORIGIN_2_SERVICE_NAME = os.getenv("ORIGIN_2_SERVICE_NAME")
ORIGIN_2_USER = os.getenv("ORIGIN_2_USER")
ORIGIN_2_PASSWORD = os.getenv("ORIGIN_2_PASSWORD")


# SQL Server: 
DATA_BASE_DESTINO = os.getenv("DATA_BASE_DESTINO")
SQL_SERVER_HOST_NAME = os.getenv("SQL_SERVER_HOST_NAME")




#### Data Dictionnary ####

DATA_DICT_FILE = "Data_Dict.xlsx" 

# Nombres columnas
COLUMNA_CAMPO = 'STG CAMPO ORIGEN'
COLUMNA_TABLA = 'STG TABLA ORIGEN'
COLUMNA_TIPO = 'STG TIPO'
COLUMNA_LONGITUD = 'STG SIZE'
COLUMNA_PRECISION = 'STG PRECISION'
COLUMNA_ESCALA = 'STG SCALE'
COLUMNA_QUERY = "QUERY"
COLUMNA_ORIGEN = "ORIGEN"

#### PARA SCRIPTS SQL SERVER

# Column Names for STG and ODS
STG_CAMPOS = COLUMNA_CAMPO
STG_TABLAS = COLUMNA_TABLA
STG_TIPO = COLUMNA_TIPO
STG_SIZE = COLUMNA_LONGITUD
STG_PRECISION = COLUMNA_PRECISION
STG_SCALE = COLUMNA_ESCALA

ODS_CAMPOS = 'ODS CAMPO ORIGEN'
ODS_TABLAS = 'ODS TABLA ORIGEN'
ODS_TIPO = 'ODS TIPO'
ODS_SIZE = 'ODS SIZE'
ODS_PRECISION = 'ODS PRECISION'
ODS_SCALE = 'ODS SCALE'



